# Generated by Django 6.0.1 on 2026-02-05 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_courses_certificate_courses_slug_coursecareerrole_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecareerrole',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='courseproject',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='coursetechnology',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='courses',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='next_batch',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='coursecareerrole',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseproject',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursetechnology',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CourseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('note', models.CharField(help_text='Example: Next batch in Feb 2026', max_length=100)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='pages.courses')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Certificate Included', max_length=150)),
                ('description', models.CharField(default='Industry-Recognized Certificate', max_length=200)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='pages.courses')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(default='Enroll Course Now', max_length=50)),
                ('url', models.URLField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cta', to='pages.courses')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_lpa', models.PositiveIntegerField()),
                ('max_lpa', models.PositiveIntegerField()),
                ('description', models.CharField(default='Average salary for freshers to 2 years exp.', max_length=150)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='pages.courses')),
            ],
        ),
    ]
