# Generated by Django 6.0.3 on 2026-04-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_coursecareerrole_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('discount_percentage', models.PositiveIntegerField(blank=True, help_text='Discount percentage (e.g., 20 for 20%)', null=True)),
                ('discount_amount', models.PositiveIntegerField(blank=True, help_text='Fixed discount amount in rupees', null=True)),
                ('deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='pages.courses')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
